FORMAT: 1A
HOST: www.google.com

# DigitalGlobe Sample Service
Welcome to the DigitalGlobe Alpha service definition

# Group Ancillary Data

## Ancillary Actions [/ancillary]

### Retrieve a piece of ancillary [GET]
Request a piece of ancillary data

+ Request Plain Text Message

    + Headers
            
            Accept: text/plain

+ Response 200 (text/plain)

    + Body
    
            Hello

+ Request JSON Message

    + Headers
    
            Accept: application/json
        
+ Response 200 (application/json)

    + Body
    
            {"message": "Hello"}
        
