FORMAT: 1A
HOST: www.google.com

# DigitalGlobe Sample Service
Welcome to the DigitalGlobe Alpha service definition

# Group Ancillary Data

## GET /ancillary
+ Headers

        Content-type: application/json

+ Response 200 (text/plain)

    + Body 
    
        ```
        Hello
        ```

+ Response 200 (application/json)

    + Body
    
        ```
        {"message":"Hello"}

