FORMAT: 1A
HOST: www.google.com

# DigitalGlobe Sample Service
Welcome to the DigitalGlobe Alpha service definition

# Group Ancillary Data

## Query Ancillary By ID [/ancillary/{id}]

### Retrieve a piece of ancillary [GET]
Request a piece of ancillary data

+ Parameters
    
    + id (number) ... Identifier of the ancillary data you want

+ Response 200 (application/xml)

    + Body
    
        ```
        <Ancillary><Path>/asdf/asdf</Path></Ancillary>
        ```

## Query Ancillary By Sensor and Time Range [/ancillary/{sensor}/{?starttime}{?endtime}]

### Retrieve ancillary by Sensor and Time Range  [GET]
Request ancillary data

+ Parameters
    
    + sensor (required, string,`WV01, WV02`) ... Valid Sensor
    + starttime (string) ... XML Time Formated String
    + endtime (string) ... XML Time Formated String

+ Response 200 (application/xml)

    + Body
    
        ```
        <Ancillary><Path>/asdf/asdf</Path></Ancillary>
        ```
    

## Create Ancillary Actions [/ancillary]

### Save a new piece of ancillary [POST]

+ Request (application/xml)

    + Body
    
        ```
        <AncillaryData><AncillaryType>FPE</AncillaryType><SensorVehicle>WV02</SensorVehicle><StartTime>2012-05-20T07:15:08.597780Z</StartTime><EndTime>2012-05-20T07:15:20.209717Z<EndTime></AncillaryData>
        ```
            
+ Response 201 (application/xml)

    + Body
    
        ```
        <CallStatus><Id>123</Id><Status>CREATED</Status></CallStatus>
        ```
